[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Railway will automatically set PORT environment variable
# Volume mounts for persistent storage
[[deploy.environmentVariables]]
name = "DATA_ROOT"
value = "/data"

[[deploy.environmentVariables]]
name = "DEBUG"
value = "false"

# Redis configuration - will be set when Redis service is added
# [[deploy.environmentVariables]]
# name = "REDIS_URL"
# value = "${{Redis.REDIS_URL}}"
